# madlib by juliana

adjective1 = input("give me an adjective that ends with -est: ")
holiday = input("give me an holiday: ")
noun1 = input("give me a noun: ")
noun2 = input("give me another noun: ")
verb1 = input("give me a present-tense verb: ")
noun3 = input("give me a present-tense noun: ")
adjective2 = input("give me a adjective: ")
noun4 = input("give me a noun: ")
verb2 = input("give me a verb: ")
emotion1 = input("give me an emotion: ")
emotion2 = input("give me another emotion: ")
adverb1 = input("give me an adverb: ")
person = input("give me a person: ")
verb3 = input("give me a verb: ")
verb4 = input("give me a verb with -ing: ")
adverb2 = input("give me an adverb: ")
verb5 = input("give me a verb: ")
adjective3 = input("give me an adjective: ")

print(f"What is the {adjective1} {holiday} gift?")
print(f"Well you would want to get your {noun1} a {noun2},")
print(f"and {verb1} a {noun3} of yours.")
print(f"You should not get a {adjective2} {noun4} that can {verb2},")
print(f"that would make {noun1} {emotion1}.")
print(f"To make them feel {emotion2},")
print(f"you should instead go to {person} and")
print(f"ask if you can {verb3} with them.")
print(f"If they don't like {verb4}, {adverb2} {verb5} with them!")
print(f"It'll make a {adjective3} gift!")